# Generated by Django 3.2.4 on 2021-06-05 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
